# Generated by Django 4.0.4 on 2022-04-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('img', models.ImageField(upload_to='img/')),
                ('description', models.TextField()),
            ],
        ),
    ]
