# Generated by Django 4.0.4 on 2022-04-30 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_course_courses_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='courses',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
