# Generated by Django 4.0.4 on 2022-04-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_added_courses_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
