# Generated by Django 4.1.7 on 2023-06-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
