# Generated by Django 4.1.7 on 2023-06-08 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joining_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
