# Generated by Django 4.1.7 on 2023-06-03 08:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('img', models.ImageField(upload_to='img/')),
                ('description', models.TextField(max_length=150)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\VATSAL\\Desktop\\Practice\\Django\\newskills\\MySkills\\myskills\\media'), upload_to='pdf/')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
    ]
