# Generated by Django 4.1.7 on 2023-05-17 11:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_pdf_file_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pdf_file',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\VATSAL\\Desktop\\Practice\\Django\\newskills\\MySkills\\myskills\\media'), upload_to='media/pdf/'),
        ),
    ]
