# Generated by Django 4.1.7 on 2023-05-23 12:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pdf_file',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\VATSAL\\Desktop\\Practice\\Django\\newskills\\MySkills\\myskills\\media'), upload_to='pdf/'),
        ),
    ]
